# -*- coding: utf-8 -*-
"""Untitled49.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1olNM6yZeZlVmgivPt1cjkdZhRSrRWqOv
"""

# Commented out IPython magic to ensure Python compatibility.
!pip install kivy
# %gui qt

pip install buildozer

from kivy.app import App
from kivy.uix.gridlayout import GridLayout
from kivy.uix.button import Button
from kivy.uix.label import Label
from kivy.uix.popup import Popup
from kivy.uix.boxlayout import BoxLayout

class TicTacToeApp(App):
    def build(self):
        self.board = [None] * 9  # 3x3 grid
        self.turn = 'X'  # 'X' starts
        self.buttons = []

        layout = GridLayout(cols=3, padding=10, spacing=10)

        for i in range(9):
            btn = Button(font_size=40, on_press=self.on_button_press)
            self.buttons.append(btn)
            layout.add_widget(btn)

        self.label = Label(text="Player X's turn", font_size=24, size_hint_y=None, height=50)

        main_layout = BoxLayout(orientation='vertical')
        main_layout.add_widget(self.label)
        main_layout.add_widget(layout)

        return main_layout

    def on_button_press(self, instance):
        if instance.text == '':  # Button is empty, can be pressed
            instance.text = self.turn
            self.check_winner()
            self.turn = 'O' if self.turn == 'X' else 'X'  # Switch turn
            self.label.text = f"Player {self.turn}'s turn"

    def check_winner(self):
        # Define all possible winning combinations
        winning_combinations = [
            [0, 1, 2], [3, 4, 5], [6, 7, 8],  # horizontal
            [0, 3, 6], [1, 4, 7], [2, 5, 8],  # vertical
            [0, 4, 8], [2, 4, 6]  # diagonal
        ]

        for combo in winning_combinations:
            if self.buttons[combo[0]].text == self.buttons[combo[1]].text == self.buttons[combo[2]].text != '':
                self.show_winner(self.buttons[combo[0]].text)
                return

        if all(btn.text != '' for btn in self.buttons):  # Check if it's a draw
            self.show_winner('Draw')

    def show_winner(self, winner):
        if winner == 'Draw':
            winner_text = "It's a draw!"
        else:
            winner_text = f"Player {winner} wins!"

        popup_layout = BoxLayout(orientation='vertical', padding=10)
        popup_label = Label(text=winner_text, font_size=24)
        popup_layout.add_widget(popup_label)

        popup_btn = Button(text="Play Again", size_hint_y=None, height=50)
        popup_btn.bind(on_press=self.reset_game)
        popup_layout.add_widget(popup_btn)

        self.popup = Popup(title='Game Over', content=popup_layout, size_hint=(None, None), size=(400, 300))
        self.popup.open()

    def reset_game(self, instance):
        # Reset the game
        for btn in self.buttons:
            btn.text = ''
        self.turn = 'X'
        self.label.text = "Player X's turn"
        self.popup.dismiss()

if __name__ == '__main__':
    TicTacToeApp().run()